### ISSUE TITLE
A couple errors being thrown to look at

### ISSUE THREAD

**Issue by alphabitnz** [5-star/plugin.video.last_played#23]
These aren't causing Kodi to crash, but are interfering with this addon's functionality until a skin reload.

```
2022-01-16 03:19:59.032 T:696166 WARNING <general>: CPythonInvoker(7, /Users/myusername/Library/Application Support/Kodi/addons/plugin.video.last_played/default.py): the python script "/Users/myusername/Library/Application Support/Kodi/addons/plugin.video.last_played/default.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon4xbmc7MonitorE
```

```
2022-01-16 12:15:11.023 T:1352870   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'NameError'>
                                                   Error Contents: name 'ListItem' is not defined
                                                   Traceback (most recent call last):
                                                     File "/Users/myusername/Library/Application Support/Kodi/addons/plugin.video.last_played/addon.py", line 129, in <module>
                                                       list_items("*", list_size)
                                                     File "/Users/myusername/Library/Application Support/Kodi/addons/plugin.video.last_played/addon.py", line 84, in list_items
                                                       li = ListItem(lang(30030))
                                                   NameError: name 'ListItem' is not defined
                                                   -->End of Python script error report<--
```

**Comment by 5-star** [comment]
Which Device, Version and skin?

Could not reproduce it on Android and Windows, V19 and V20

**Comment by alphabitnz** [comment]
> Which Device, Version and skin?
> 
> Could not reproduce it on Android and Windows, V19 and V20

Mac OS Monterey
Kodi 19.3.0 2022-01-04 Nightly
Embruary Skin

Just checked through my current logfile and it only seems to occur when I've been using Last Played as a custom widget for the skin's homepage widgets module, so perhaps it is in fact an incompatibility with a call in that skin's custom widgets code.
